name: test-0abcdef0-sidalit
license: Unlicense
base: core24
version: '0.1'
summary: Amazing useless snap for testing
description: |
  Nothing more than the summary
website:
  - https://github.com/sidalit/test-snap
platforms:
  amd64:
  arm64:

grade: stable
confinement: strict

apps:
  colors:
    command: bin/colors

parts:
  colors:
    plugin: dump
    source: .
