name: publish

on:
  workflow_dispatch:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build snap
        uses: canonical/action-build@v1

      - name: Publish snap
        uses: sidalit/stack-utils/snap-publish@IENG-1706-reusable-build-release-snap-action
        with:
          store-credentials: ${{ secrets.STORE_LOGIN }}
